server:
  error:
    include-message: always
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: administrator
    url: jdbc:postgresql://localhost:5432/simantri
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update